
package com.bank.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankPortType", targetNamespace = "http://www.bank.com/types")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankPortType {


    /**
     * 
     * @param loginRequest
     * @return
     *     returns com.bank.types.LoginResponse
     */
    @WebMethod(operationName = "Login")
    @WebResult(name = "LoginResponse", targetNamespace = "http://www.bank.com/types", partName = "LoginResponse")
    public LoginResponse login(
        @WebParam(name = "LoginRequest", targetNamespace = "http://www.bank.com/types", partName = "LoginRequest")
        LoginRequest loginRequest);

    /**
     * 
     * @param withdrawRequest
     * @return
     *     returns com.bank.types.WithdrawResponse
     */
    @WebMethod(operationName = "Withdraw")
    @WebResult(name = "WithdrawResponse", targetNamespace = "http://www.bank.com/types", partName = "WithdrawResponse")
    public WithdrawResponse withdraw(
        @WebParam(name = "WithdrawRequest", targetNamespace = "http://www.bank.com/types", partName = "WithdrawRequest")
        WithdrawRequest withdrawRequest);

    /**
     * 
     * @param historyRequest
     * @return
     *     returns com.bank.types.HistoryResponse
     */
    @WebMethod(operationName = "History")
    @WebResult(name = "HistoryResponse", targetNamespace = "http://www.bank.com/types", partName = "HistoryResponse")
    public HistoryResponse history(
        @WebParam(name = "HistoryRequest", targetNamespace = "http://www.bank.com/types", partName = "HistoryRequest")
        HistoryRequest historyRequest);

    /**
     * 
     * @param transferRequest
     * @return
     *     returns com.bank.types.TransferResponse
     */
    @WebMethod(operationName = "Transfer")
    @WebResult(name = "TransferResponse", targetNamespace = "http://www.bank.com/types", partName = "TransferResponse")
    public TransferResponse transfer(
        @WebParam(name = "TransferRequest", targetNamespace = "http://www.bank.com/types", partName = "TransferRequest")
        TransferRequest transferRequest);

    /**
     * 
     * @param paymentRequest
     * @return
     *     returns com.bank.types.PaymentResponse
     */
    @WebMethod(operationName = "Payment")
    @WebResult(name = "PaymentResponse", targetNamespace = "http://www.bank.com/types", partName = "PaymentResponse")
    public PaymentResponse payment(
        @WebParam(name = "PaymentRequest", targetNamespace = "http://www.bank.com/types", partName = "PaymentRequest")
        PaymentRequest paymentRequest);

}
