
package com.bank.types;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankPortTypeService", targetNamespace = "http://www.bank.com/types", wsdlLocation = "http://localhost:8080/ws/bank.wsdl")
public class BankPortTypeService
    extends Service
{

    private final static URL BANKPORTTYPESERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKPORTTYPESERVICE_EXCEPTION;
    private final static QName BANKPORTTYPESERVICE_QNAME = new QName("http://www.bank.com/types", "BankPortTypeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/bank.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKPORTTYPESERVICE_WSDL_LOCATION = url;
        BANKPORTTYPESERVICE_EXCEPTION = e;
    }

    public BankPortTypeService() {
        super(__getWsdlLocation(), BANKPORTTYPESERVICE_QNAME);
    }

    public BankPortTypeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKPORTTYPESERVICE_QNAME, features);
    }

    public BankPortTypeService(URL wsdlLocation) {
        super(wsdlLocation, BANKPORTTYPESERVICE_QNAME);
    }

    public BankPortTypeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKPORTTYPESERVICE_QNAME, features);
    }

    public BankPortTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankPortTypeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankPortType
     */
    @WebEndpoint(name = "BankPortTypeSoap11")
    public BankPortType getBankPortTypeSoap11() {
        return super.getPort(new QName("http://www.bank.com/types", "BankPortTypeSoap11"), BankPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankPortType
     */
    @WebEndpoint(name = "BankPortTypeSoap11")
    public BankPortType getBankPortTypeSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bank.com/types", "BankPortTypeSoap11"), BankPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKPORTTYPESERVICE_EXCEPTION!= null) {
            throw BANKPORTTYPESERVICE_EXCEPTION;
        }
        return BANKPORTTYPESERVICE_WSDL_LOCATION;
    }

}
